/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {}

export interface components {
  schemas: {
    Contract: {
      slug: string;
      handle: string;
      type: string;
      loop: string;
      description: string;
      version: components["schemas"]["Semver"];
      data: { [key: string]: any };
      requires: { [key: string]: any }[];
      provides: { [key: string]: any }[];
    };
    Semver: string;
  };
}

export interface operations {}
