/* eslint @typescript-eslint/no-empty-interface: 0 */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {}

export interface components {
	schemas: {
		Blueprint: components['schemas']['Contract'] & { [key: string]: any } & {
			type?: 'meta.blueprint';
			layout?: components['schemas']['BlueprintLayout'];
			skeleton?: { [key: string]: any };
		};
		BlueprintLayout: { [key: string]: any };
		Contract: {
			type: string;
		} & { [key: string]: any };
	};
}

export interface operations {}
